openapi: "3.0.2"
info:
  title: Demo Admin App API
  version: "1.0"
  description: API for interacting with Demo Admin App resources
servers:
  - url: https://api.server.test/v1
tags:
  - name: Contacts
paths:
  /contacts:
    get:
      summary: List Contacts
      operationId: listContacts
      description: List Contacts
      tags:
        - Contacts
      parameters:
        - name: search
          in: query
          description: "Filter for name substring match"
          schema:
            type: string
        - name: limit
          in: query
          description: "Page limit size for pagination"
          schema:
            type: integer
        - name: offset
          in: query
          description: "Offset pagination"
          schema:
            type: integer
      responses:
        200:
          description: A paged array of Contacts
          content:
            application/json:
              schema:
                properties:
                  contacts:
                    $ref: "#/components/schemas/Contacts"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
    post:
      summary: Create Contact
      operationId: createContact
      description: Create Contact
      tags:
        - Contacts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WriteContact"
      responses:
        201:
          description: Contact created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
  /contacts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: "The ID of the Contact to get"
        schema:
          type: string
    get:
      summary: Get Contact
      operationId: getContact
      tags:
        - Contacts
      responses:
        200:
          description: Get Contact
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        404:
          description: Object not found
    put:
      summary: Update Contact
      operationId: updateContact
      tags:
        - Contacts
      description: Update Contact
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        200:
          description: Contact successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        400:
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
    delete:
      summary: Delete Contact
      operationId: deleteContact
      tags:
        - Contacts
      description: Delete Contact
      responses:
        204:
          description: Contact successfully deleted
        404:
          description: Object not found, or already deleted

components:
  schemas:
    Contacts:
      type: array
      items:
        $ref: "#/components/schemas/Contact"
    Contact:
      type: object
      required:
        - first_name
        - last_name
      properties:
        id:
          type: string
          readOnly: true
          description: The contacts record id
          example: 5badc33ced994854aaa91556
        first_name:
          type: string
          description: The contacts first name
          example: Mike
        last_name:
          type: string
          description: The contacts last name
          example: Whitehead
        company_name:
          type: string
          description: The contacts company name
          example: NVIDIA
        phone_number:
          type: string
          description: The contacts phone number
          example: 408-967-4578
    WriteContact:
      type: object
      required:
        - first_name
        - last_name
      properties:
        first_name:
          type: string
          description: The contacts first name
          example: Mike
        last_name:
          type: string
          description: The contacts last name
          example: Whitehead
        company_name:
          type: string
          description: The contacts company name
          example: NVIDIA
        phone_number:
          type: string
          description: The contacts phone number
          example: 408-967-4578
    Errors:
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
    Error:
      properties:
        message:
          type: string
          example: "name required"
    Pagination:
      properties:
        limit:
          type: integer
          example: 10
        offset:
          type: integer
          example: 0
        total_count:
          type: integer
          example: 100
