apiVersion: v1
kind: Service
metadata:
  name: demo-admin-frontend
  labels:
    app: demo-admin-app
    component: demo-admin-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo-admin-app
    component: demo-admin-frontend
