kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: demo-admin-app
    component: demo-admin-app-db
  name: demo-admin-app-db
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  
