apiVersion: v1
kind: Service
metadata:
  name: demo-admin-app-db
  labels:
    app: demo-admin-app
    component: demo-admin-app-db
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: demo-admin-app
    component: demo-admin-app-db
